# Generated by Django 5.1.2 on 2024-11-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pie',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
