# Generated by Django 5.1.2 on 2024-11-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pies', '0002_pie_votes'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pie',
            name='votes',
        ),
        migrations.AddField(
            model_name='pie',
            name='voters',
            field=models.ManyToManyField(related_name='voted_pie', to='register.user'),
        ),
    ]
